version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
  
  commander:
    build: .
    depends_on:
      - mqtt5
    command: ["uv", "run", "/app/src/llsg/commander/audio.py"]
    devices:
      - "/dev/snd:/dev/snd"
    container_name: commander
  
  sensor:
    build: .
    depends_on:
      - mqtt5
    command: ["uv", "run", "/app/src/llsg/sensor/sensor.py"]
    container_name: sensor
  
  stimulator:
    build: .
    depends_on:
      - mqtt5
    command: ["uv", "run", "/app/src/llsg/stimulator/stimulator.py"]
    container_name: stimulator

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt5-network
